"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = [ "s" ], run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = [ "c", "a" ], run = "plugin compress", desc = "Archive selected files" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "K", run = "arrow -50%", desc = "Move cursor up half page" },
  { on = "J", run = "arrow 50%", desc = "Move cursor down half page" },
  { on = "<A-k>", run = "arrow -5", desc = "Move cursor up half page" },
  { on = "<A-j>", run = "arrow 5", desc = "Move cursor down half page" },
  { on = [ "f", "g" ], run = "plugin fg", desc = "find file by content (fuzzy match)" },
  { on = [ "f", "f" ], run = "filter --smart", desc = "Filter files" },
  { on = [ "f", "l" ], run = "plugin searchjump", desc = "Flash" },
  { on = [ "f", "d" ], run = "search --via=fd", desc = "Search files by name using fd" },
  { on = [ "<C-y>" ], run = 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', desc = "Copy to clipboard" },
  { on = "I", run = "create --dir", desc = "Create a dir" },
  { on = "i", run = "create", desc = "Create a file" },
  { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Root of Git Repo" },
  { on = "H", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
  { on = "L", run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
  { on = "<", run = "tab_swap -1", desc = "Swap current tab with previous tab" },
  { on = ">", run = "tab_swap 1", desc = "Swap current tab with next tab" },

  # Bookmarks Plugin!
  { on = [ "M" ], run = "plugin bookmarks save", esc = "Save current position as a bookmark" },
  { on = [ "'" ], run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
  { on = [ "b", "d" ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
  # { on = [ "b", "D" ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks" },
  # Custom Git command to fuzzy search git tracked files
  # { on = [ "<C-f>" ], run = "yazi --picker='fzf' --interactive --cmd 'shell git ls-files'", desc = "Fuzzy Search git-tracked files" },
  # { on = [ "g", "f" ], run = "shell -- git ls-files | fzf | xargs ya emit open", desc = "Fuzzy Search git-tracked files" },
]

append_keymap = [
  { on = [
    "e",
  ], run = "open", desc = "Open the selected files" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Open the selected files interactively" },
]

[completion]
# prepend_keymap = [
#   { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
#   { on = "<C-j>", run = "arrow 1", desc = "Move cursor down" },
# ]
