require("plugins_config.autopairs")
-- require("plugins_config.bufferline")
require("plugins_config.conform")
require("plugins_config.Copilot")
require("plugins_config.evil_lualine")
require("plugins_config.fidget")
require("plugins_config.focus")
require("plugins_config.gitsigns")
require("plugins_config.indent-blankline")
require("plugins_config.inlay-diagnostic")
-- require("plugins_config.inlay-hint")
require("plugins_config.LSPs")
require("plugins_config.Markdown-preview")
require("plugins_config.NoiceConfig")
require("plugins_config.nvim-lsp")
require("plugins_config.nvim-surround")
require("plugins_config.nvim-web-devicons")
require("plugins_config.Oil")
require("plugins_config.project")
require("plugins_config.ranger")
require("plugins_config.startify")
-- require("plugins_config.statuscol")
require("plugins_config.Tabby")
require("plugins_config.telekasten")
require("plugins_config.telescope")
require("plugins_config.treesitter")
require("plugins_config.trim")
