require("plugins_config.trim")
require("plugins_config.indent-blankline")
-- require("plugins_config.nvim-tree")
require("plugins_config.nvim-web-devicons")
require("plugins_config.ranger")
require("plugins_config.evil_lualine")
require("plugins_config.focus")
require("plugins_config.telescope")
require("plugins_config.gitsigns")
require("plugins_config.treesitter")
require("plugins_config.LSPs")
require("plugins_config.Copilot")
require("plugins_config.noice")
require("plugins_config.Tabby")
