-- require("themes_config.catppuccin")
-- require("themes_config.kanagawa")
-- require("themes_config.everforest")
require("themes_config.sonokai")
-- require("themes_config.oak")
-- require("themes_config.colorscheme")
-- require("themes_config.tokyo_dark")
-- require("themes_config.gruvbox")
-- require("themes_config.gruvbox-material")
-- require("themes_config.edge")
require("themes_config.themes_overrides")
