-- require("themes_config.catppuccin")
-- require("themes_config.colorscheme")
-- require("themes_config.edge")
-- require("themes_config.everforest")
-- require("themes_config.gruvbox-material")
-- require("themes_config.kanagawa")
-- require("themes_config.neon")
-- require("themes_config.nightfox")
-- require("themes_config.one-nvim")
-- require("themes_config.onebuddy")
require("themes_config.onedark")
-- require("themes_config.tokyo_dark")
require("themes_config.themes_overrides")
