require("plugins_config.better-whitespace")
require("plugins_config.fzf")
require("plugins_config.ranger")
-- require("plugins_config.lualine")
require("plugins_config.evil_lualine")
-- require("plugins_config.nvim-tree.config")
-- require("plugins_config.treesitter")
-- require("plugins_config.lightline")
